### ISSUE TITLE
[Feature or enhancement request]

### ISSUE THREAD

**Issue by Lucas-Bide** [KCarlile/flashchord#104] opened 2023-10-14 18:14 UTC
## Background

Could you please extend the BPM lower range to 40 BPM (or lower) on the BPM slider?

**Comment by KCarlile** [comment] 2023-10-15 20:34
Thanks, @Lucas-Bide! I've added your specific note to #32 as this is a duplicate of that ticket.

**Closed by KCarlile** 2023-10-15 20:34 UTC
Labels: duplicate, enhancement
